#!/usr/bin/with-contenv sh

# make our folders
mkdir -p \
	/config/www/dokuwiki

# install dokuwiki
if [ ! -e "/config/www/dokuwiki/index.php" ]; then
curl -o /tmp/dokuwiki.tgz -L https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
tar xf /tmp/dokuwiki.tgz -C /config/www/dokuwiki --strip-components=1
rm /tmp/dokuwiki.tgz
fi

# permissions
chown -R abc:abc \
	/config
