#!/usr/bin/with-contenv bash

USER_DIRECTORY=(\
    "conf" \
    "data/attic" \
    "data/media" \
    "data/media_attic" \
    "data/media_meta" \
    "data/meta" \
    "data/pages" \
    "lib/plugins" \
    "lib/tpl"
    )

## Make data directories
[[ ! -d /config/dokuwiki/data ]]
    mkdir -p /config/dokuwiki/data

[[ ! -d /config/dokuwiki/lib/ ]]
    mkdir -p /config/dokuwiki/lib/

## Move user folders to persistent storage
for i in "${USER_DIRECTORY[@]}"; do 
    [[ ! -d /config/dokuwiki/${i} ]] && \
        [[ -d /app/dokuwiki/"${i}" ]] && \
        mv /app/dokuwiki/"${i}" /config/dokuwiki/"${i}"/
done

## Remove user folders
for i in "${USER_DIRECTORY[@]}"; do 
[[ -d /app/dokuwiki/"${i}" ]] && \
    rm -rf /app/dokuwiki/"${i}"
done

## Make Symlinks
for i in "${USER_DIRECTORY[@]}"; do 
[[ ! -L /app/dokuwiki/"${i}" ]] && \
    ln -s /config/dokuwiki/"${i}" /app/dokuwiki/"${i}"
done

## Bump php upload max filesize and post max size to 100MB by default
grep -qxF 'upload_max_filesize' /config/php/php-local.ini || echo 'upload_max_filesize = 100MB' >> /config/php/php-local.ini
grep -qxF 'post_max_size' /config/php/php-local.ini || echo 'post_max_size = 100MB' >> /config/php/php-local.ini

## Remove install.php once setup & enable pretty urls to work after setting .htaccess method in admin panel.
if [[ -f /config/dokuwiki/conf/local.php ]]; then
    rm -rf /app/dokuwiki/install.php && \
    sed -i -e 's/#location/location/g' \
        /config/nginx/site-confs/default && \
    echo "Existing install found install.php not available"
else
    echo "Go to http://IP-ADDRESS:PORT/install.php to configure your install then restart your container when finished to remove install.php"
fi

# permissions
echo "[cont-init.d] Setting permissions this may take some time"
chown -R abc:abc \
    /app/dokuwiki \
    /config
